### PR TITLE
Update the CRC website per Tanya and Janet's requets

### PR DESCRIPTION
**Pull request by sapols**
**The changes introduced in this PR can be previewed at:** http://bouldercrc.fiatflux.is/

This PR:
-  reorganizes the contents of the home page, putting some content in their own pages
-  puts a button for the food assistance page on the home page
-  reorganizes the navigation header and adds some new pages to it, like a calendar and FAQs

The Food Assistance page was added to the main site after I forked the repo, so I had to add that to my fork manually. GitHub is showing that it can't automatically merge this PR and I think that has something to do with it. I tested the preview site thoroughly and concluded that all my code is correct and what Tanya and Janet want. I'm open for discussion.

### CODE REVIEW

**Comment by sapols** [comment]
@gregor-robinson I'm guessing the merge conflicts with the food assistance pages are in part due to my header being different than that of the main site. The page works in the preview site, so hopefully the resolution is to toss out the conflicts from the main page to keep my changes.

**Comment by fiatflux** [comment]
This is looking really nice! Don't worry about the conflicts; I can easily fix them.
We're going to need to collapse some of the top buttons into a menu (or tweak the CSS, but that sounds much harder) ... this has problems with overlap depending on screen size and zoom. See top left of screenshot taken at default zoom on my laptop in Firefox:
image

Edit: also the "donate ..." button on index.html word-wraps in a confusing way on my phone. How about just "Donate"?

**Comment by sapols** [comment]
@fiatflux Huh... I don't know how to do that. I just blindly followed what Tanya wanted in the header.

**Comment by sapols** [comment]
Screen Shot 2019-10-03 at 12 31 11 PM

Sometimes the nav items will drop to a second row when the width shrinks, like "CALENDAR" in this screenshot. It seems like it should be possible in CSS to assert that items should move to the second row sooner to avoid that overlap. Do you know how to do that?

**Comment by fiatflux** [comment]
Same procedure as the "Menu" drop-down but maybe we can fold "Who we are", "What we have accomplished", and "Our demands" into one "About" button?

**Comment by fiatflux** [comment]
> Screen Shot 2019-10-03 at 12 31 11 PM
> 
> Sometimes the nav items will drop to a second row when the width shrinks, like "CALENDAR" in this screenshot. It seems like it should be possible in CSS to assert that items should move to the second row sooner to avoid that overlap. Do you know how to do that?

I'm afraid not. I would begin by trying something like
```
<div class="row">
<div "class=2u 12u(narrower)">
[logo]
</div>
<div "class=10u 12u(narrower)">
[buttons]
</div>
</div>
```
but I have no idea if that works within the header there or what consequences it might come with, especially considering the drop-down would add complexity. I think the easiest approach to start with is a second drop-down.

**Comment by sapols** [comment]
About the "Donate to our food assistance" button: I think just "Donate" would be confusing because it doesn't link to the general donate page, it links to the food assistance page. Janet wanted that specific wording on the button. It wouldn't look weird on mobile if the buttons weren't the same orange as the background (i.e. like in the desktop site where the orange is lighter). CSS can fix that.

Your "About" menu solution seems reasonable. I'll run it by Tanya.

**Comment by sapols** [comment]
@fiatflux I fixed everything! Tanya liked the "About" nav item idea so I did that. And to keep Janet's wording on the "Donate to our food assistance fund" button I changed the CSS to keep the darker background behind the buttons on mobile. I also noticed a word overlap issue on mobile with the nav item "What we have accomplished" and I fixed it by shortening it to "What we've accomplished". The changes are live at: http://bouldercrc.fiatflux.is/

I think we're ready to merge.

**Comment by sapols** [comment]
@fiatflux ?

**Comment by fiatflux** [comment]
Looks great! Heads up though, your editor mixes spaces and tabs. I didn't bother to fix all the inconsistency but it made git diff glow.

**Pull request merged**
